language: node_js
node_js:
  - '12'
install:
  - npm ci
script:
  - npm run prettier
  - npm run lint
  - npm run test
services:
  - postgresql
before_script:
  - psql -c 'create database 'tubertest';' -U postgres
